name: chattingapp
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  rounded_loading_button: ^1.0.0
  firebase_auth : ^0.14.0+5
  google_sign_in : ^4.0.7
  flutter_facebook_login : ^2.0.1
  cloud_firestore: ^0.12.9+5
  provider : ^3.1.0+1
  popup_menu : ^1.0.5
  auto_size_text : ^ 2.1.0
  url_launcher : ^ 5.5.3
  firebase_core: ^0.4.0
  slider_button : ^0.5.0
  mobile_popup :  ^1.2.0
  firebase_messaging : ^5.0.2
  cloud_functions : ^0.5.0
  image_picker: ^0.5.3+1
  firebase_storage : ^3.1.6
  font_awesome_flutter : ^8.8.1
  basic_utils: ^1.2.0
  auto_refresh_list_view : ^1.1.0
  dio : ^3.0.9
  path_provider : ^1.6.11
  pull_to_refresh: ^1.4.5
  flutter_spinkit: ^3.1.0
  flutter_speed_dial: ^1.0.9
  giffy_dialog : ^1.8.0
  intl : ^0.16.1
  flutter_advanced_networkimage : ^0.7.0
  circular_countdown_timer : ^0.0.4
  floating_action_bubble : ^1.1.1
  rflutter_alert: ^1.0.2
  simple_animations : ^2.2.1
  flutter_email_sender : ^3.0.1
  flutter_local_notifications : ^1.4.4+4
  google_fonts : ^0.2.0
  popup_box : ^0.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path : "images/chatpad.jpg"
  ios : true
  android : true




# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/facebook-logo.png
    - images/google-logo.png
    - images/username-logo1.webp
    - images/usernamee.png
    - images/shubh.jpg
    - images/chatbg.jpg
    - images/send.png
    - images/logo.png
    - images/nullimage1.jpg
    - images/logotxt.jpg
    - images/logo.jpg
    - images/group_icon.jpg
    - images/group_icon.png
    - images/A.png
    - images/B.png
    - images/C.png
    - images/D.png
    - images/E.png
    - images/F.png
    - images/G.png
    - images/H.png
    - images/I.png
    - images/J.png
    - images/K.png
    - images/L.png
    - images/M.png
    - images/N.png
    - images/O.png
    - images/P.png
    - images/Q.png
    - images/R.png
    - images/S.png
    - images/T.png
    - images/U.png
    - images/V.png
    - images/W.png
    - images/X.png
    - images/linked.png
    - images/Y.png
    - images/Z.png
    - images/group_name.png
    - images/google.jpg
    - images/instagram.png
    - images/chatpad.jpg
    - images/bg_img.jpg
    - images/oops1.png
    - images/oops1.jpg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for t he font. For
  # example:
  fonts:
     - family: Yellowtail
       fonts:
         - asset: fonts/Yellowtail-Regular.ttf
         - asset: fonts/Notable-Regular.ttf


     - family: Sriracha
       fonts:
         - asset: fonts/Sriracha-Regular.ttf

     - family: HindMadurai
       fonts:
         - asset: fonts/HindMadurai-Regular.ttf

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
